version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: admin
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    command: "kong start"

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - "1337:1337"
    depends_on:
      - kong

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/app?schema=public"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"

volumes:
  pgdata:
